<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\Admin\SkillController;
use App\Http\Controllers\Admin\ProjectController;
use App\Http\Controllers\Admin\MessageController;
use Illuminate\Support\Facades\Route;

// ═══════════════════════════════════════════════════════════════
// PUBLIC ROUTES — accessible by everyone (no login required)
// ═══════════════════════════════════════════════════════════════

Route::get('/',          [PortfolioController::class, 'home'])->name('home');
Route::get('/portfolio', [PortfolioController::class, 'portfolio'])->name('portfolio');
Route::get('/contact',   [PortfolioController::class, 'contact'])->name('contact');
Route::post('/contact',  [PortfolioController::class, 'sendMessage'])->name('contact.send');


// ═══════════════════════════════════════════════════════════════
// DASHBOARD — Breeze redirects here after login
// Route name MUST stay 'dashboard' — Breeze hardcodes this
// ═══════════════════════════════════════════════════════════════

Route::get('/dashboard', function () {
    return redirect()->route('admin.skills.index');
})->middleware(['auth', 'verified'])->name('dashboard');


// ═══════════════════════════════════════════════════════════════
// PROFILE ROUTES — generated by Breeze, keep as-is
// ═══════════════════════════════════════════════════════════════

Route::middleware('auth')->group(function () {
    Route::get('/profile',    [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile',  [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});


// ═══════════════════════════════════════════════════════════════
// ADMIN ROUTES — protected, must be logged in
//
// Because this group has ->name('admin.'), every route name
// inside gets 'admin.' prepended automatically:
//   ->name('dashboard')      becomes  'admin.dashboard'
//   ->name('skills.index')   becomes  'admin.skills.index'
// ═══════════════════════════════════════════════════════════════

Route::prefix('admin')
     ->name('admin.')
     ->middleware(['auth', 'verified'])
     ->group(function () {

    // ✅ CORRECT: just 'dashboard' here
    //    group prefix makes the final name → 'admin.dashboard'
    // ❌ WRONG:  'admin.dashboard' here would make → 'admin.admin.dashboard'
    Route::get('/', fn() => redirect()->route('admin.skills.index'))
         ->name('dashboard');

    // ── Skills CRUD ──────────────────────────────────────────
    Route::resource('skills', SkillController::class)->except('show');

    // ── Projects CRUD ────────────────────────────────────────
    Route::resource('projects', ProjectController::class)->except('show');

    // ── Messages (inbox — read + delete only) ────────────────
    Route::get('messages',              [MessageController::class, 'index'])->name('messages.index');
    Route::get('messages/{message}',    [MessageController::class, 'show'])->name('messages.show');
    Route::delete('messages/{message}', [MessageController::class, 'destroy'])->name('messages.destroy');
    Route::delete('messages',           [MessageController::class, 'destroyAll'])->name('messages.destroyAll');
});


// ═══════════════════════════════════════════════════════════════
// AUTH ROUTES — login, register, logout, forgot-password
// Auto-generated by Breeze — do not modify
// ═══════════════════════════════════════════════════════════════

require __DIR__.'/auth.php';